---
title: Making Interactive Maps with {leaflet}
output-location: slide
---



```{r}
options(tigris_use_cache = TRUE)
```


```{r}
#| eval: true
library(leaflet)
library(tidyverse)
library(tidycensus)
library(janitor)
library(tigris)
library(scales)
library(sf)
```

```{r}
speak_language_other_than_english <-
  get_acs(
    geography = "county",
    variable = "S1601_C01_003",
    summary_var = "S1601_C01_001",
    geometry = TRUE
  ) |>
  clean_names() |>
  mutate(pct = estimate / summary_est) |>
  select(name, pct)
```


```{r}
#| eval: false
speak_language_other_than_english |>
  mapview::mapview()
```

### Backgrounds (Map Tiles)

::: {.notes}
https://leaflet-extras.github.io/leaflet-providers/preview/
:::


```{r}
leaflet() |>
  addTiles() |>
  addMarkers(lng = 174.768, lat = -36.852, popup = "The birthplace of R")
```

---

```{r}
#| code-line-numbers: "2"
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addMarkers(lng = 174.768, lat = -36.852, popup = "The birthplace of R")
```

---

```{r}
#| code-line-numbers: "2"
leaflet() |>
  addProviderTiles("Stadia.StamenToner") |>
  addMarkers(lng = 174.768, lat = -36.852, popup = "The birthplace of R")
```

### Add Polygons


```{r}
speak_language_other_than_english_wgs84 <-
  speak_language_other_than_english |>
  st_transform(crs = 4326)
```

```{r}
#| echo: false
#| eval: false
speak_language_other_than_english_wgs84 |>
  write_sf("data/speak_language_other_than_english_wgs84.geojson")
```

```{r}
leaflet() |>
  addTiles() |>
  addPolygons(data = speak_language_other_than_english_wgs84)
```

#### Adjust Borders

```{r}
leaflet() |>
  addTiles() |>
  addPolygons(
    data = speak_language_other_than_english_wgs84,
    weight = 0
  )
```

---

```{r}
leaflet() |>
  addTiles() |>
  addPolygons(
    data = speak_language_other_than_english_wgs84,
    weight = 1,
    color = "red"
  )
```

### Add Points

```{r}
portland_drinking_fountains <-
  read_sf("data/portland_drinking_fountains.geojson")
```

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addCircles(data = portland_drinking_fountains)
```

### Add Lines

```{r}
library(tigris)

multnomah_county_roads <-
  roads(state = "OR", county = "Multnomah")
```

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolylines(data = multnomah_county_roads)
```

### Show/Hide Layers

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron", group = "Map") |>
  addProviderTiles("Esri.WorldImagery", group = "Satellite") |>
  addCircles(
    data = portland_drinking_fountains,
    group = "Drinking Fountains",
    color = "green"
  ) |>
  addPolylines(
    data = multnomah_county_roads,
    group = "Roads",
    weight = 1,
    color = "purple"
  ) |>
  addLayersControl(,
    baseGroups = c(
      "Map",
      "Satellite"
    ),
    overlayGroups = c(
      "Roads",
      "Drinking Fountains"
    )
  ) |>
  hideGroup("Roads")
```

### Your Turn {.your-turn}

- Import the [data I've created on the number of refugees from each country in the world](https://raw.githubusercontent.com/rfortherestofus/mapping-with-r-v2/refs/heads/main/data/refugees.geojson)

- Map this using {leaflet}. All countries will be the same color at this point (we'll change that in the next lesson).