---
title: Making Choropleth Maps with {leaflet}
---

```{r}
library(leaflet)
library(tidyverse)
library(tidycensus)
library(janitor)
library(tigris)
library(scales)
library(sf)
```


```{r}
speak_language_other_than_english_wgs84_with_labels <-
  read_sf("data/speak_language_other_than_english_wgs84_with_labels.geojson")
```

```{r}
speak_language_other_than_english_wgs84_with_labels
```

### Create a Continuous Palette

```{r}
pal <-
  colorNumeric(
    palette = "viridis",
    domain = speak_language_other_than_english_wgs84_with_labels$pct
  )

leaflet() |>
  setView(-93.65, 42.0285, zoom = 2) |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84_with_labels,
    fillColor = ~ pal(pct),
    color = "white",
    weight = 0.75,
    popup = ~text_label
  )
```

### Create a Binned Color Palette

```{r}
binpal <-
  colorBin(
    palette = "viridis",
    domain = speak_language_other_than_english_wgs84_with_labels$pct,
    bins = 4
  )

leaflet() |>
  setView(-93.65, 42.0285, zoom = 2) |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84_with_labels,
    fillColor = ~ binpal(pct),
    color = "white",
    weight = 0.75,
    popup = ~text_label
  )
```

---

### Specify Breaks

```{r}
binpal_explicit_bins <-
  colorBin(
    palette = "viridis",
    domain = speak_language_other_than_english_wgs84_with_labels$pct,
    bins = c(0, 0.25, 0.5, 0.75, 1)
  )

leaflet() |>
  setView(-93.65, 42.0285, zoom = 2) |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84_with_labels,
    fillColor = ~ binpal_explicit_bins(pct),
    color = "white",
    weight = 0.75,
    popup = ~text_label
  )
```

### Legends

```{r}
leaflet() |>
  setView(-93.65, 42.0285, zoom = 2) |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84_with_labels,
    fillColor = ~ binpal_explicit_bins(pct),
    color = "white",
    weight = 0.75,
    popup = ~text_label
  ) |>
  addLegend(
    position = "bottomright",
    pal = binpal_explicit_bins,
    values = speak_language_other_than_english_wgs84_with_labels$pct,
    labFormat = labelFormat(
      transform = function(x) x * 100,
      suffix = "%"
    ),
    opacity = 0.5
  )
```

### Your Turn {.your-turn}

- Using the code to make your map from the last lesson on refugee populations, turn your map into a choropleth, with different shading for countries with higher refugee populations. 