---
title: Making Dot and Bubble Maps with {leaflet}
---




```{r}
#| echo: false
options(tigris_use_cache = TRUE)
```

### Dot Maps

```{r}
library(leaflet)
library(tidyverse)
library(tidycensus)
library(janitor)
library(tigris)
library(scales)
library(sf)
library(leaflegend)
```

```{r}
portland_drinking_fountains <-
  read_sf("data/drinking_fountains.geojson")
```

```{r}
portland_drinking_fountains |>
  st_drop_geometry() |>
  count(FOUNTAINSTYLE)
```

### Create Color Palette

```{r}
pal_discrete <- colorFactor(
  palette = c(
    "#7fc97f",
    "#beaed4",
    "#fdc086",
    "#ffff99",
    "#386cb0",
    "#f0027f"
  ),
  na.color = "gray70",
  domain = fct(portland_drinking_fountains$FOUNTAINSTYLE)
)
```

### Make Dot Map

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addCircles(
    data = portland_drinking_fountains,
    stroke = FALSE,
    fillColor = ~ pal_discrete(FOUNTAINSTYLE),
    radius = 10,
    fillOpacity = 1
  )
```

### Bubble Maps

```{r}
oregon_places <-
  read_sf("data/oregon_places.geojson") |>
  st_transform(crs = 4326)
```

```{r}
oregon_places
```

---

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addCircles(
    data = oregon_places,
    radius = ~ population / 100,
    label = ~name,
    stroke = FALSE,
    fillOpacity = 0.5
  ) |>
  addLegendSize(
    values = c(0, 500000),
    color = "blue",
    shape = "circle",
    opacity = .5,
    breaks = 10
  )
```

### Your Turn {.your-turn}

- Use this code to import centroids (i.e. one point in the center of each country)

. . .

```{r}
refugees_country_centroids <-
  read_sf(
    "https://raw.githubusercontent.com/rfortherestofus/mapping-with-r-v2/refs/heads/main/data/refugees_country_centroids.geojson"
  )
```

- Make a bubble map, with the size of each bubble relative to the size of the refugee population from that country.