---
title: Spatial Filters
---

```{r}
#| echo: false
#| eval: false

# library(sf)
# library(janitor)

# read_sf("https://hub.arcgis.com/api/v3/datasets/2110697e9c1e42f3a87f75c310da64f1_78/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1") |>
#   clean_names() |>
#   st_make_valid() |>
#   select(objectid, ramp_style) |>
#   mutate(
#     ramp_style = case_when(
#       ramp_style %in% c("NONE", "UNKNOWN") ~ "Unimproved",
#       .default = "Improved"
#     )
#   ) |>
#   write_sf("data/improved_corners_polygons.geojson")
```

### Import Data

```{r}
library(sf)
library(tidyverse)

improved_corners <-
  read_sf("data/improved_corners.geojson")

improved_corners
```

---

```{r}
city_council_districts <-
  read_sf("data/city_council_districts.geojson")

city_council_districts
```

### Can Do Same Things with st_join()


```{r}
st_join(
  improved_corners,
  city_council_districts
) |>
  filter(district == "District 1")
```

### Introducing st_filter()

```{r}
district_1_boundaries <-
  city_council_districts |>
  filter(district == "District 1")
```

```{r}
improved_corners |>
  st_filter(district_1_boundaries)
```

### Spatial Predicates

```{r}
improved_corners_polygons <-
  read_sf("data/improved_corners_polygons.geojson")

improved_corners_polygons
```

---

```{r}
#| eval: false

library(mapview)

mapview(improved_corners_polygons)
```

---

```{r}
district_1_corners <-
  improved_corners_polygons |>
  st_filter(district_1_boundaries)

district_1_corners
```

::: {.notes}
Talk about predicates for st_filter
https://r-spatial.github.io/sf/reference/st_join.html

Show how default is st_intersects
:::

---

```{r}
#| eval: false
mapview(district_1_boundaries) +
  mapview(district_1_corners)
```

::: {.notes}
Focus on eastern borders (https://show.rfor.us/LkbJtNF1) because you see the difference between this predicate and st_within
:::

---

```{r}
improved_corners_polygons |>
  st_filter(
    district_1_boundaries,
    .predicate = st_intersects
  )
```

---

```{r}
improved_corners_polygons |>
  st_filter(
    district_1_boundaries,
    .predicate = st_within
  )
```

---
  
```{r}
#| code-line-numbers: "5"
district_1_corners_within <-
  improved_corners_polygons |>
  st_filter(
    district_1_boundaries,
    .predicate = st_within
  )

district_1_corners_within
```

---

```{r}
#| eval: false

mapview(district_1_boundaries) +
  mapview(district_1_corners_within)
```

### Your Turn {.your-turn}

- Use the `st_filter()` function to only keep the traffic signals within the Southwest sextant



