---
title: Mapping with R
---

```{r}
#| echo: false
options(pillar.sigfig = 7)
```

# Welcome to Course {.inverse}

## Welcome to Mapping with R {.inverse}

{{< include slides-welcome-to-mapping.qmd >}}

# Geospatial Data: Vector Data {.inverse}

## Simple Features Data {.inverse}

::: {.notes}
Talk about how it has become standard

Do same thing I do in [book](https://book.rfortherestofus.com/maps.html#a-brief-primer-on-geospatial-data)
:::

{{< include slides-sf-data.qmd >}}

## Accessing Raw Geospatial Data {.inverse}

{{< include slides-accessing-raw-geospatial-data.qmd >}}

## Turning Data Frames into `sf` Objects {.inverse}

{{< include slides-turning-data-frames-into-sf-objects.qmd >}}

## Geocoding {.inverse}

{{< include slides-geocoding.qmd >}}

## Accessing Geospatial Data Through Packages {.inverse}

{{< include slides-accessing-geospatial-data-through-packages.qmd >}}

# Static Maps {.inverse}

## Mapping with ggplot {.inverse}

{{< include slides-mapping-with-ggplot.qmd >}}

## Choropleth Maps {.inverse}

{{< include slides-choropleth-maps.qmd >}}

## Dot and Bubble Maps {.inverse}

{{< include slides-dot-and-bubble-maps.qmd >}}



## Adding Text to Maps {.inverse}

{{< include slides-adding-text-to-maps.qmd >}}

## Choosing a Projection {.inverse}

{{< include slides-choosing-a-projection.qmd >}}

# Interactive Maps {.inverse}

## Making Interactive Maps with {leaflet} {.inverse}

<!-- {{< include slides-making-interactive-maps-with-leaflet.qmd >}} -->

## Adding Text Labels to {leaflet} Maps {.inverse}

<!-- {{< include slides-adding-text-labels-to-leaflet-maps.qmd >}} -->

## Making Choropleth Maps with {leaflet} {.inverse}

<!-- {{< include slides-making-choropleth-maps-with-leaflet.qmd >}} -->

## Making Dot and Bubble Maps with {leaflet} {.inverse}

<!-- {{< include slides-making-dot-and-bubble-maps-with-leaflet.qmd >}} -->

## Making Interactive Maps with Other Packages {.inverse}

<!-- {{< include slides-making-interactive-maps-with-other-packages.qmd >}} -->

# Geospatial Data Analysis

## Joining Data Frmes with sf Objects {.inverse}

<!-- {{< include slides-joining-data-frames-with-sf-objects.qmd >}} -->

## Joining Two sf Objects {.inverse}

<!-- {{< include slides-joining-two-sf-objects.qmd >}} -->

## Combining Multiple sf Objects {.inverse}

<!-- {{< include slides-combining-multiple-sf-objects.qmd >}} -->

## Spatial Overlays {.inverse}

<!-- {{< include slides-spatial-overlays.qmd >}} -->

# Maps that Require Complicated Geospatial Analysis

## Heatmaps {.inverse}

<!-- {{< include slides-heatmaps.qmd >}} -->

## Flow Maps

<!-- {{< include slides-flow-maps.qmd >}} -->

# Raster Data {.inverse}

# Wrapping Up {.inverse}

## Should This Be a Map? {.inverse}

<!-- {{< include slides-should-this-be-a-map.qmd >}} -->

## Wrapping up Mapping with R {.inverse}

<!-- {{< include slides-wrapping-up-mapping-with-r.qmd >}} -->

