---
title: Adding Text Labels to {leaflet} Maps
---


```{r}
library(leaflet)
library(tidyverse)
library(tidycensus)
library(janitor)
library(tigris)
library(scales)
library(sf)
```

```{r}
speak_language_other_than_english_wgs84 <-
  read_sf("data/speak_language_other_than_english_wgs84.geojson")
```

### Text

#### Labels

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84,
    weight = 1
  )
```

---

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84,
    weight = 1,
    label = ~name
  )
```

#### Popups

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84,
    weight = 1,
    popup = ~name
  )
```

### Create Better Labels


```{r}
speak_language_other_than_english_wgs84_with_labels <-
  speak_language_other_than_english_wgs84 |>
  mutate(
    text_label = str_glue(
      "<b>{percent(pct, accuracy = 0.1)}</b> of the population of <b>{name}</b> speaks a language other than English"
    )
  )
```

---

```{r}
leaflet() |>
  addProviderTiles("CartoDB.Positron") |>
  addPolygons(
    data = speak_language_other_than_english_wgs84_with_labels,
    weight = 1,
    popup = ~text_label
  )
```

```{r}
#| echo: false
#| eval: false

speak_language_other_than_english_wgs84_with_labels |>
  select(name, pct, text_label) |>
  write_sf("data/speak_language_other_than_english_wgs84_with_labels.geojson")
```

### Your Turn {.your-turn}

- Using the code to make your map from the last lesson on refugee populations, add a label and/or popup that show the number of refugees from each country.